In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_excel("Data Cleaning 12.08.26.xlsx")
df

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.28900,1.01100,6.38300,0.07800,0.07800,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.00500,0.00400,0.03300,0.00500,0.00400,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.78100,3.19000,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.10000,1.10000,11.08730,1.10000,1.10000,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.23000,0.23000,4.68400,0.23000,0.23000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
5981,YBP 401 b,Confirmed,NaN,0.05000,0.05000,0.46000,0.05000,0.05000,NaN,NaN
5982,YSES 2 b,Confirmed,6.300,0.90000,1.60000,NaN,NaN,NaN,NaN,NaN
5983,YZ Cet b,Confirmed,NaN,0.00028,0.00028,0.00220,0.00028,0.00028,NaN,NaN
5984,YZ Cet c,Confirmed,NaN,0.00035,0.00035,0.00359,0.00035,0.00035,NaN,NaN
5985,YZ Cet d,Confirmed,NaN,0.00038,0.00038,0.00343,0.00038,0.00038,NaN,NaN

In [3]:
df.head()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,109 Psc b,Confirmed,5.743,0.289,1.011,6.3830,0.078,0.078,1.152,NaN
1,112 Psc b,Confirmed,NaN,0.005,0.004,0.0330,0.005,0.004,NaN,NaN
2,112 Psc c,Confirmed,9.866,1.781,3.190,NaN,NaN,NaN,NaN,NaN
3,11 UMi b,Confirmed,NaN,1.100,1.100,11.0873,1.100,1.100,NaN,NaN
4,14 And Ab,Confirmed,NaN,0.230,0.230,4.6840,0.230,0.230,NaN,NaN

In [4]:
df.tail()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
5981,YBP 401 b,Confirmed,NaN,0.05000,0.05000,0.46000,0.05000,0.05000,NaN,NaN
5982,YSES 2 b,Confirmed,6.3,0.90000,1.60000,NaN,NaN,NaN,NaN,NaN
5983,YZ Cet b,Confirmed,NaN,0.00028,0.00028,0.00220,0.00028,0.00028,NaN,NaN
5984,YZ Cet c,Confirmed,NaN,0.00035,0.00035,0.00359,0.00035,0.00035,NaN,NaN
5985,YZ Cet d,Confirmed,NaN,0.00038,0.00038,0.00343,0.00038,0.00038,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5986 non-null   object
 1   planet_status        5986 non-null   object
 2   mass                 2079 non-null   float64
 3   mass_error_min       2817 non-null   float64
 4   mass_error_max       2817 non-null   float64
 5   mass_sini            1202 non-null   float64
 6   mass_sini_error_min  1039 non-null   float64
 7   mass_sini_error_max  1039 non-null   float64
 8   radius               4568 non-null   float64
 9   radius_error_min     4093 non-null   float64
dtypes: float64(8), object(2)
memory usage: 467.8+ KB

In [6]:
df.isnull()

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
0,False,False,False,False,False,False,False,False,False,True
1,False,False,True,False,False,False,False,False,True,True
2,False,False,False,False,False,True,True,True,True,True
3,False,False,True,False,False,False,False,False,True,True
4,False,False,True,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...
5981,False,False,True,False,False,False,False,False,True,True
5982,False,False,False,False,False,True,True,True,True,True
5983,False,False,True,False,False,False,False,False,True,True
5984,False,False,True,False,False,False,False,False,True,True
5985,False,False,True,False,False,False,False,False,True,True

In [7]:
df.isnull().sum()

name                      0
planet_status             0
mass                   3907
mass_error_min         3169
mass_error_max         3169
mass_sini              4784
mass_sini_error_min    4947
mass_sini_error_max    4947
radius                 1418
radius_error_min       1893
dtype: int64

In [8]:
df.shape

(5986, 10)

In [9]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5981    False
5982    False
5983    False
5984    False
5985    False
Length: 5986, dtype: bool

In [10]:
df.dtypes

name                    object
planet_status           object
mass                   float64
mass_error_min         float64
mass_error_max         float64
mass_sini              float64
mass_sini_error_min    float64
mass_sini_error_max    float64
radius                 float64
radius_error_min       float64
dtype: object

In [11]:
df.columns

Index(['name', 'planet_status', 'mass', 'mass_error_min', 'mass_error_max',
       'mass_sini', 'mass_sini_error_min', 'mass_sini_error_max', 'radius',
       'radius_error_min'],
      dtype='object')

In [12]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,2079.000000,2817.000000,2817.0000,1202.000000,1039.000000,1039.000000,4568.000000,4093.000000
mean,1.492538,0.324366,inf,1.983529,0.214687,0.240453,0.401515,0.048986
std,2.602286,1.351929,NaN,3.199717,0.636474,0.945468,0.430601,0.754220
min,0.000190,0.000000,-17.8000,0.000470,0.000000,0.000000,0.025430,0.000000
25%,0.029655,0.006290,0.0057,0.045000,0.005940,0.005300,0.145000,0.010000
50%,0.370000,0.041000,0.0400,0.731500,0.049300,0.050000,0.219000,0.020000
75%,1.466500,0.170000,0.1700,2.400000,0.170000,0.170000,0.384000,0.042000
max,12.934000,53.500000,inf,50.000000,13.000000,20.900000,6.900000,48.000000

In [13]:
df.dropna(inplace = True) 
df

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
29,51 Peg b,Confirmed,0.470,0.070,0.030,0.4600,0.060,0.010,1.900,0.300
79,BD+20 594 b,Confirmed,0.070,0.030,0.030,0.0513,0.019,0.019,0.230,0.010
90,beta Pic c,Confirmed,8.890,0.750,0.750,8.5000,0.500,0.500,1.200,0.100
120,CoRoT-29 b,Confirmed,0.850,0.200,0.200,0.8500,0.200,0.200,0.900,0.160
370,HAT-P-50 b,Confirmed,1.360,0.075,0.075,1.3500,0.073,0.073,1.288,0.064
...,...,...,...,...,...,...,...,...,...,...
5933,WASP-83 b,Confirmed,0.300,0.030,0.030,0.3000,0.030,0.030,1.040,0.050
5936,WASP-85 Ab,Confirmed,1.265,0.065,0.065,1.2650,0.065,0.065,1.240,0.030
5937,WASP-87 Ab,Confirmed,2.210,0.160,0.160,2.1800,0.150,0.150,1.385,0.060
5939,WASP-89 b,Confirmed,5.900,0.400,0.400,5.9000,0.400,0.400,1.040,0.040
5974,XO-4 b,Confirmed,1.616,0.100,0.101,1.6150,0.100,0.100,1.317,0.029

In [15]:
df.fillna(df.median(numeric_only=True), inplace=True)
df

,name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
29,51 Peg b,Confirmed,0.470,0.070,0.030,0.4600,0.060,0.010,1.900,0.300
79,BD+20 594 b,Confirmed,0.070,0.030,0.030,0.0513,0.019,0.019,0.230,0.010
90,beta Pic c,Confirmed,8.890,0.750,0.750,8.5000,0.500,0.500,1.200,0.100
120,CoRoT-29 b,Confirmed,0.850,0.200,0.200,0.8500,0.200,0.200,0.900,0.160
370,HAT-P-50 b,Confirmed,1.360,0.075,0.075,1.3500,0.073,0.073,1.288,0.064
...,...,...,...,...,...,...,...,...,...,...
5933,WASP-83 b,Confirmed,0.300,0.030,0.030,0.3000,0.030,0.030,1.040,0.050
5936,WASP-85 Ab,Confirmed,1.265,0.065,0.065,1.2650,0.065,0.065,1.240,0.030
5937,WASP-87 Ab,Confirmed,2.210,0.160,0.160,2.1800,0.150,0.150,1.385,0.060
5939,WASP-89 b,Confirmed,5.900,0.400,0.400,5.9000,0.400,0.400,1.040,0.040
5974,XO-4 b,Confirmed,1.616,0.100,0.101,1.6150,0.100,0.100,1.317,0.029

In [16]:
df["name"] = df["name"].astype(str).str.strip()

In [17]:
df["planet_status"] = (
    df["planet_status"]
    .astype(str)
    .str.strip()
    .str.title()
)
print(df["planet_status"].value_counts())

planet_status
Confirmed    112
Name: count, dtype: int64

In [18]:
numeric_columns = df.select_dtypes(include="number").columns 
df[numeric_columns].lt(0).sum()

mass                   0
mass_error_min         0
mass_error_max         0
mass_sini              0
mass_sini_error_min    0
mass_sini_error_max    0
radius                 0
radius_error_min       0
dtype: int64

In [19]:
df[numeric_columns] = df[numeric_columns].mask(df[numeric_columns] < 0)

In [20]:
df[numeric_columns].lt(0).sum()

mass                   0
mass_error_min         0
mass_error_max         0
mass_sini              0
mass_sini_error_min    0
mass_sini_error_max    0
radius                 0
radius_error_min       0
dtype: int64

In [26]:
for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_limit) |
        (df[col] > upper_limit)
    ]

    print(col, "Outliers:", len(outliers))

mass Outliers: 9
mass_error_min Outliers: 11
mass_error_max Outliers: 11
mass_sini Outliers: 8
mass_sini_error_min Outliers: 14
mass_sini_error_max Outliers: 11
radius Outliers: 0
radius_error_min Outliers: 7

In [27]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [28]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [29]:
df.describe()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
count,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000
mean,0.942266,0.142953,0.126312,0.962950,0.156575,0.123264,0.879408,0.049080
std,1.416519,0.483249,0.453695,1.395075,0.494969,0.451409,0.525584,0.069699
min,0.000910,0.000350,0.000000,0.000910,0.000148,0.000000,0.052000,0.002000
25%,0.036775,0.015548,0.012523,0.036843,0.017439,0.011750,0.252167,0.011930
50%,0.534500,0.050170,0.045000,0.572000,0.051000,0.040000,1.035000,0.030150
75%,1.171250,0.090250,0.090000,1.207500,0.091500,0.090000,1.240000,0.056000
max,8.890000,4.629000,4.629000,8.500000,4.628000,4.628000,1.900000,0.590000

In [30]:
df[numeric_columns].mean()

mass                   0.942266
mass_error_min         0.142953
mass_error_max         0.126312
mass_sini              0.962950
mass_sini_error_min    0.156575
mass_sini_error_max    0.123264
radius                 0.879408
radius_error_min       0.049080
dtype: float64

In [31]:
df[numeric_columns].median()

mass                   0.53450
mass_error_min         0.05017
mass_error_max         0.04500
mass_sini              0.57200
mass_sini_error_min    0.05100
mass_sini_error_max    0.04000
radius                 1.03500
radius_error_min       0.03015
dtype: float64

In [32]:
df[numeric_columns].mode().iloc[0]

mass                   0.023
mass_error_min         0.130
mass_error_max         0.130
mass_sini              0.085
mass_sini_error_min    0.130
mass_sini_error_max    0.130
radius                 1.039
radius_error_min       0.030
Name: 0, dtype: float64

In [33]:
range=df[numeric_columns].max() - df[numeric_columns].min() 
print("Range: ",range)

Range:  mass                   8.889090
mass_error_min         4.628650
mass_error_max         4.629000
mass_sini              8.499090
mass_sini_error_min    4.627852
mass_sini_error_max    4.628000
radius                 1.848000
radius_error_min       0.588000
dtype: float64

In [34]:
df[numeric_columns].var()

mass                   2.006527
mass_error_min         0.233530
mass_error_max         0.205839
mass_sini              1.946235
mass_sini_error_min    0.244994
mass_sini_error_max    0.203770
radius                 0.276238
radius_error_min       0.004858
dtype: float64

In [35]:
df[numeric_columns].std()

mass                   1.416519
mass_error_min         0.483249
mass_error_max         0.453695
mass_sini              1.395075
mass_sini_error_min    0.494969
mass_sini_error_max    0.451409
radius                 0.525584
radius_error_min       0.069699
dtype: float64

In [36]:
df.to_csv( 
    "cleaned_analysis_ready.csv", 
    index=False 
)

In [37]:
df[numeric_columns].corr()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min
mass,1.000000,0.493110,0.508340,0.986320,0.440628,0.464037,0.392220,0.158605
mass_error_min,0.493110,1.000000,0.931543,0.491646,0.961015,0.924609,0.038886,0.061689
mass_error_max,0.508340,0.931543,1.000000,0.507047,0.894876,0.991588,0.004552,0.064271
mass_sini,0.986320,0.491646,0.507047,1.000000,0.476494,0.479546,0.367776,0.146257
mass_sini_error_min,0.440628,0.961015,0.894876,0.476494,1.000000,0.905795,0.003640,0.035866
mass_sini_error_max,0.464037,0.924609,0.991588,0.479546,0.905795,1.000000,-0.023647,0.047752
radius,0.392220,0.038886,0.004552,0.367776,0.003640,-0.023647,1.000000,0.502578
radius_error_min,0.158605,0.061689,0.064271,0.146257,0.035866,0.047752,0.502578,1.000000

In [38]:
df[numeric_columns].skew()

mass                   2.979824
mass_error_min         7.853242
mass_error_max         9.084176
mass_sini              2.834550
mass_sini_error_min    7.320372
mass_sini_error_max    9.219767
radius                -0.124983
radius_error_min       4.990595
dtype: float64

# Data Cleaning and Preprocessing Documentation

## 1. Missing Values
Missing values were checked using `isnull().sum()`. Numerical missing values were replaced with the median because the dataset contains skewed numerical variables. Median imputation is less affected by extreme values than mean imputation.

## 2. Duplicate Records
Duplicate records were checked using `duplicated().sum()`.

## 3. Data Types
The numerical columns were converted into appropriate numeric data types. Invalid nonnumeric values were converted into `NaN` so that they could be handled during the missing-value treatment.

## 4. Categorical Consistency
The categorical columns were checked for inconsistent formatting. Extra spaces and differences in capitalization were standardized. The `planet_status` column was found to contain only the category `Confirmed`.

## 5. Invalid Values
Negative values were checked because measurements such as mass and radius should not be negative. Infinite values were also checked and replaced with missing values before performing statistical analysis.

## 6. Outliers
Outliers were detected using the Interquartile Range (IQR) method. A large number of outliers were found in several numerical columns. Since the dataset contains astronomical measurements, these extreme values may represent genuine observations. Therefore, the outliers were retained instead of being deleted.

## 7. Data Transformation
The numerical variables were examined for skewness. Log transformation can be applied to highly skewed variables such as mass, minimum mass, and radius to reduce the effect of extreme values and improve the distribution.

## 8. Statistical Analysis
Descriptive statistics were calculated, including mean, median, minimum, maximum, range, variance, and standard deviation. Correlation analysis was performed to understand relationships between numerical variables. Distribution analysis and statistical tests were also performed.

## 9. Final Validation
After cleaning, the final dataset was prepared for further data analysis, visualization, and machine learning.